version: '3.8'

services:
  app:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    ports:
      - 3000:3000
