version: '3.8'

services:
  app:
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    ports:
      - 3000:3000
